name: Build Windows EXE

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 获取代码
      uses: actions/checkout@v4

    - name: 安装 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 安装打包需要的运行库
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 pandas openpyxl pyinstaller

    - name: 执行 EXE 打包命令
      run: |
        pyinstaller --noconsole --onefile --name "自习登记系统" main.py

    - name: 上传打包好的成品
      uses: actions/upload-artifact@v4
      with:
        name: 自习登记系统-Windows版
        path: dist/自习登记系统.exe
